### ISSUE TITLE
Unexpected map_to parsing behavior in conjunct list

### ISSUE THREAD

**Issue by will62794** [tlaplus-community/tree-sitter-tlaplus#87] opened 2023-11-19 05:34 UTC
I appear to be encountering some unexpected behavior when parsing the `map_to` infix operator (`:>`) inside a conjunction list. For example,
```tla
---- MODULE simple_tlc_fn ----

Init ==
    /\ x = 0 :> 0
    /\ y = 1 :> 1

====
```
parses as 
```
source_file [0, 0] - [7, 0])
  module [0, 0] - [6, 4])
    header_line [0, 0] - [0, 4])
    name: identifier [0, 12] - [0, 25])
    header_line [0, 26] - [0, 30])
    operator_definition [2, 0] - [4, 17])
      name: identifier [2, 0] - [2, 4])
      def_eq [2, 5] - [2, 7])
      definition: bound_infix_op [3, 4] - [4, 17])
        lhs: bound_infix_op [3, 4] - [3, 17])
          lhs: conj_list [3, 4] - [3, 13])
            conj_item [3, 4] - [3, 12])
              bullet_conj [3, 4] - [3, 6])
              bound_infix_op [3, 7] - [3, 12])
                lhs: identifier_ref [3, 7] - [3, 8])
                symbol: eq [3, 9] - [3, 10])
                rhs: nat_number [3, 11] - [3, 12])
          symbol: map_to [3, 13] - [3, 15])
          rhs: nat_number [3, 16] - [3, 17])
        symbol: land [4, 4] - [4, 6])
        rhs: bound_infix_op [4, 7] - [4, 17])
          lhs: identifier_ref [4, 7] - [4, 8])
          symbol: eq [4, 9] - [4, 10])
          rhs: bound_infix_op [4, 11] - [4, 17])
            lhs: nat_number [4, 11] - [4, 12])
            symbol: map_to [4, 13] - [4, 15])
            rhs: nat_number [4, 16] - [4, 17])
    double_line [6, 0] - [6, 4])

```
but if I simply use a different infix operator (e.g. `+`), as follows:
```tla
---- MODULE simple_tlc_fn ----

Init ==
    /\ x = 0 + 0
    /\ y = 1 + 1

====
```
this parses as a `conj_list` with a `conj_item` for each conjunct line:
```
source_file [0, 0] - [7, 0])
  module [0, 0] - [6, 4])
    header_line [0, 0] - [0, 4])
    name: identifier [0, 12] - [0, 25])
    header_line [0, 26] - [0, 30])
    operator_definition [2, 0] - [6, 0])
      name: identifier [2, 0] - [2, 4])
      def_eq [2, 5] - [2, 7])
      definition: conj_list [3, 4] - [6, 0])
        conj_item [3, 4] - [3, 16])
          bullet_conj [3, 4] - [3, 6])
          bound_infix_op [3, 7] - [3, 16])
            lhs: identifier_ref [3, 7] - [3, 8])
            symbol: eq [3, 9] - [3, 10])
            rhs: bound_infix_op [3, 11] - [3, 16])
              lhs: nat_number [3, 11] - [3, 12])
              symbol: plus [3, 13] - [3, 14])
              rhs: nat_number [3, 15] - [3, 16])
        conj_item [4, 4] - [4, 16])
          bullet_conj [4, 4] - [4, 6])
          bound_infix_op [4, 7] - [4, 16])
            lhs: identifier_ref [4, 7] - [4, 8])
            symbol: eq [4, 9] - [4, 10])
            rhs: bound_infix_op [4, 11] - [4, 16])
              lhs: nat_number [4, 11] - [4, 12])
              symbol: plus [4, 13] - [4, 14])
              rhs: nat_number [4, 15] - [4, 16])
    double_line [6, 0] - [6, 4])
```
which is more in line with what I expected to see. 

Am I correct in thinking the first case seems unexpected? Perhaps this is related to some specific handling of the `map_to` operator, but I'm not sure.

**Comment by ahelwer** [comment] 2023-11-19 13:49
Condensed sample:
```tla
---- MODULE Test ----
Init ==
    \/ x :> 0
    \/ y :> 1
====
```
Very interesting! Will take a look in a couple hours.

**Comment by ahelwer** [comment] 2023-11-19 14:51
I believe the issue is in the external scanner here: https://github.com/tlaplus-community/tree-sitter-tlaplus/blob/d99cb5c77bb0e733176d607a0875ac30e17e1e72/src/scanner.cc#L467

I didn't add the lexing case to check for if the `:` is followed by a `>` to make the infix operator `:>`, so the scanner thinks it's a `:` in the sense of:
```
---- MODULE Test ----
op == {
  /\ A
  /\ B : x \in P
}
====
```
and thus terminates the junction list. It will be an easy fix for this issue but I should also look through the other terminating cases to see whether they're a prefix of other operators I missed.

**Comment by ahelwer** [comment] 2023-11-19 18:06
Drawing this from the `tokenize_lexeme` function in the scanner ([link](https://github.com/tlaplus-community/tree-sitter-tlaplus/blob/d99cb5c77bb0e733176d607a0875ac30e17e1e72/src/scanner.cc#L775)).

List of all tokens that are considered right delimiters (end topmost jlist) for the purposes of a jlist:

- Comma `,`
- Colon `:`
- Right parenthesis `)`
- Right square bracket `]`
- Right curly brace `}`
- Right angle bracket `>>`
- Right arrow `->`
- `THEN` keyword from `IF`/`THEN`/`ELSE`
- `ELSE` keyword from `IF`/`THEN`/`ELSE`
- `IN` keyword from `LET`/`IN`

List of all tokens that are considered terminators (end all jlists) for the purposes of a jlist:

-  Semicolon `;`
- Single line `----`
- Double line `====`
- `ASSUME`/`ASSUMPTION`/`AXIOM` keywords
- `CONSTANT`/`CONSTANTS` keywords
- `VARIABLE`/`VARIABLES` keywords
- `COROLLARY`/`LEMMA`/`PROPOSITION`/`THEOREM` keywords
- `LOCAL` keyword
- End of file

Checking all of these, the following operators have one of them as their prefix:
- Assign operator `:=` with `:` as prefix
- BNF rule operator `::=` with `:` as prefix
- Map-top operator `:>` with `:` as prefix
- Label-as construct `::` with `:` as prefix

So I think the `:>` operator is the only case not being handled. I will add a test for all of these.

**Closed** 2023-11-19 18:26 UTC

**Comment by ahelwer** [comment] 2023-11-19 18:36
@will62794 this is fixed and I cut another release containing the fix. btw do you know about the monthly TLA+ project meetings? They're pretty fun and you could talk about what you've been working on! The next one will be on Tuesday December 12th, you can find the details & meeting link in the google calendar link in this thread: https://groups.google.com/g/tlaplus/c/CpAEnrf-DHQ/m/YrORpIfSBwAJ

**Comment by will62794** [comment] 2023-11-20 00:46
@ahelwer Awesome, thanks for the quick fix. Could you remind me what the easiest way to get a new WASM build is? I don't seem to recall what I did in the past to pull in new parser changes.

And if I'm available for the next project meeting I will try to attend!

**Comment by ahelwer** [comment] 2023-11-20 01:46
The WASM build should be included in the root directory of each NPM package release.
